
services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - app.env

    depends_on:
      - db
    command: ["wait-for-it.sh","db","5432","--","./hms"]
      
  db: 
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - db.env
