
services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - app.env

    depends_on:
      - migrations

    command: ["./hms"]
    

  migrations:
    build: .
    env_file:
      - db.env
    volumes:
      - ./db/migrations:/migrations

    depends_on:
      - db
    command: >
      /bin/sh -c "
        /usr/local/bin/wait-for-it.sh db:5432 && \
        goose -dir /migrations postgres \
        \"postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}\" up
      "


  db: 
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - db.env
