
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_URL=postgresql://postgres:12345@db:5432/hms

    depends_on:
      - db
    command: ["wait-for-it.sh","db","5432","--","./hms"]
      
  db: 
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - db.env
