
services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - app.env

    depends_on:
      - migrations

    command: ["./hms"]
    restart: unless-stopped

  migrations:
    build: .
    env_file:
      - db.env
    volumes:
      - ./db/migrations:/migrations

    depends_on:
      - db
    command: >
      /bin/sh -c "
        /usr/local/bin/wait-for-it.sh db 5432 && \
        for i in 1 2 3 4 5; do
          goose -dir /migrations postgres 'postgresql://postgres:12345@db:5432/hms' up && break || sleep 3;
        done
      "




  db: 
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - db.env
