apiVersion: apps/v1
kind: Deployment
metadata:
  name: hms-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: hms
  template:
    metadata:
      labels:
        app: hms
    spec:
      containers:
        - name: hms
          image: registry.digitalocean.com/hms-reg/hms:latest
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: hms-secrets
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
