# .github/workflows/deploy.yml
name: Deploy to DOKS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DigitalOcean Container Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login registry.digitalocean.com -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG=registry.digitalocean.com/hms-reg/hms:latest
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Decode and Configure Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config
      - name: verify access to cluster
        run: kubectl get nodes
      - name: Create Kubernetes Secret
        run: |
          kubectl delete secret hms-secrets --namespace=default --ignore-not-found
          kubectl create secret generic hms-secrets \
            --from-literal=DB_URL=${{ secrets.DB_URL }} \
            --from-literal=PORT=${{ secrets.PORT }} \
            --from-literal=POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
            --from-literal=POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
            --from-literal=POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
            --namespace=default \
            --dry-run=client -o yaml | kubectl apply -f -  
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/
          kubectl rollout status deployment/hms-deployment
