name: Deploy to Private Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production  # 🔥 connect to the environment you configured!

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create app.env file from GitHub Secrets
        run: |
          echo "DB_URL=${{ secrets.DB_URL }}" > app.env;

      - name: Create db.env file from GitHub Secrets
        run: |
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" > db.env;
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> db.env;
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> db.env;


      - name: Sync project to server
        run: |
          rsync -az -e "ssh -o StrictHostKeyChecking=no" ./ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/home/ec2-user/hms-app


      - name: SSH and run docker compose
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd ~/hms-app
           docker-compose down
           docker-compose build --no-cache
           docker-compose up -d

          EOF
